zuul:
  routes:
    api-client:
      path: /api/client/**
      serviceId: ai-client
    api-client2:
      path: /api/client2/**
      serviceId: ai-client2
    service-hello:
      path: /api/service/hello/**
      serviceId: service-hello

---
#测试环境
spring:
  profiles: stg

---
#生产环境
spring:
  profiles: prd