spring:
  application:
    name: eureka_client
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

---
spring:
  application:
    name: eureka_client
  profiles: docker

server:
  port: ${AICLOUD_CORE_CLIENT_SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${AICLOUD_CORE_DISCOVER_SERVICE_HOST}:${}



